In [50]:
#Numpy 1
import numpy as np


A = np.array([[5, 6, 7],
              [8, 9, 10]])

B = np.array([[11, 12, 13],
              [14, 15, 16]])

print("Array A:")
print(A)

print("\nArray B:")
print(B)

vertical_stack = np.vstack((A, B))
print("\nVertical Stack:")
print(vertical_stack)

horizontal_stack = np.hstack((A, B))
print("\nHorizontal Stack:")
print(horizontal_stack)

Array A:
[[ 5  6  7]
 [ 8  9 10]]

Array B:
[[11 12 13]
 [14 15 16]]

Vertical Stack:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]

Horizontal Stack:
[[ 5  6  7 11 12 13]
 [ 8  9 10 14 15 16]]


In [16]:
#Numpy 2
common = np.intersect1d(A, B)
print("\nCommon elements:", common)


Common elements: []


In [32]:
#Numpy 3
indices = np.where((A >= 5) & (A <= 10))[0]  # [0] to get the array from tuple
result = A[indices]
print("Using np.where():", result)

Using np.where(): [[ 5  6  7]
 [ 5  6  7]
 [ 5  6  7]
 [ 8  9 10]
 [ 8  9 10]
 [ 8  9 10]]


In [34]:
#Numpy 4
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print("\nFiltered iris_2d:")
print(f"Shape: {filtered_iris.shape}")
print("\nFirst 10 filtered rows:")
print(filtered_iris[:10])

print(f"\nTotal rows matching criteria: {filtered_iris.shape[0]} out of {iris_2d.shape[0]}")


Filtered iris_2d:
Shape: (6, 4)

First 10 filtered rows:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]

Total rows matching criteria: 6 out of 150


In [38]:
#Pandas 1
import pandas as pd
import numpy as np
print("=" * 60)
print("1. FILTER EVERY 20TH ROW")
print("=" * 60)

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(f"Original dataframe shape: {df.shape}\n")

result = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print("Every 20th row starting from row 0:")
print(result)

1. FILTER EVERY 20TH ROW
Original dataframe shape: (93, 27)

Every 20th row starting from row 0:
   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [58]:
import pandas as pd

# Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print("Missing values before:")
print(df[['Min.Price', 'Max.Price']].isnull().sum())

df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

print("\nMissing values after:")
print(df[['Min.Price', 'Max.Price']].isnull().sum())
print(df[['Min.Price', 'Max.Price']])

Missing values before:
Min.Price    7
Max.Price    5
dtype: int64

Missing values after:
Min.Price    0
Max.Price    0
dtype: int64
    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]
